### ISSUE TITLE
MEI file not saved if only 1 image in folder

### ISSUE THREAD

**Issue by sonovice** [cemfi/vertaktoid#1]
The MEI file is not saved if there's only 1 image in the folder.

**Comment by eugene1985** [comment]
I can't reproduce this issue. It seems to work properly.

**Comment by eugene1985** [comment]
Sorry, the issue is open again. MEI file is still saved, but is ignored by openning.

**Comment by eugene1985** [comment]
Fixed. The new export/import MEI functions support the graphic tags containing the zone tags, what fixes the bug with single image.
