### ISSUE TITLE
system beginning and page beginning tags

### ISSUE THREAD

**Issue by bwbohl** [cemfi/vertaktoid#36]
`mei:sb`and `mei:pb` are by definition tags marking the beginning of a system or a page. Consequently on a page turn the order should be.

```xml
<pb/>
<sb/>
```

Vertaktoid v3.0.0-rc currently inserts them as:

```xml
<sb/>
<pb/>
```

This should be corrected

**Comment by bwbohl** [comment]
Consequently there also should be no `sb` if no measures follow on the page and no `pb` at the end of the last page

**Comment by bwbohl** [comment]
A great feature would also be to add `pb/@facs` pointing to the corresponding `surface/@xml:id`

**Comment by riedde** [comment]
I did some tests with Release 4.0.0 today. `<pb>` is occurring at the beginning (before the first measure) while `<sb>` is not. Further a `<sb>` is set before every following `<pb>`. A `<pb>` implies that a new system is beginning so it is not necessary there.
